apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment 
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{.Values.name }}
  template:
    metadata:
      labels:
        app: {{.Values.name }}
    spec:
      containers:
        - name: {{.Values.name }}
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
          # env:
          #   - name: WORDPRESS_DB_HOST
          #     value: mysql-service
          #   - name: WORDPRESS_DB_NAME
          #     value: wordpress
          #   - name: WORDPRESS_DB_USER
          #     valueFrom:
          #       secretKeyRef:
          #         name: mysql-secret
          #         key: username
          #   - name: WORDPRESS_DB_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: mysql-secret
          #         key: password
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP  # Change to NodePort or ClusterIP based on your setup
  ports:
    - port:  {{ .Values.port }}
      targetPort:  {{ .Values.port }}
      # nodePort: 30080  # Optional if using NodePort type
  selector:
    app: {{.Values.name }}
