apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.host }}  # Replace with your domain or IP address
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}  # Replace with the name of your backend Service
            port:
              number: {{ .Values.port }} # Replace with the port number your backend Service listens on
